local anim8 = require 'anim8.anim8'
local state = require 'core.animator.state'

local logic = {}

function logic.updateGrid()
    if not state.image then return end
    local fw = tonumber(state.inputState.frameWidth.text) or 32
    local fh = tonumber(state.inputState.frameHeight.text) or 32
    local l = tonumber(state.inputState.left.text) or 0
    local t = tonumber(state.inputState.top.text) or 0
    local b = tonumber(state.inputState.border.text) or 0
    
    local imgW, imgH = state.image:getDimensions()
    state.grid = anim8.newGrid(fw, fh, imgW, imgH, l, t, b)
    
    logic.createAnimation()
end

function logic.createAnimation()
    if not state.image or not state.grid then return end
    state.errorMessage = ""
    
    if #state.selectedFrames == 0 then
        state.animation = nil
        state.generatedCode = ""
        return
    end
    
    local dur = tonumber(state.inputState.duration.text)
    if not dur or dur <= 0 then
        state.errorMessage = "Invalid duration."
        state.animation = nil
        return
    end
    
    local framesArr = {}
    local framesStrArgs = {}
    for i, f in ipairs(state.selectedFrames) do
        table.insert(framesArr, f.x)
        table.insert(framesArr, f.y)
        table.insert(framesStrArgs, string.format("%d,%d", f.x, f.y))
    end
    
    local framesSuccess, frames = pcall(function() return state.grid(unpack(framesArr)) end)
    if not framesSuccess then
        state.errorMessage = "Frames out of bounds."
        state.animation = nil
        return
    end
    
    local animSuccess, anim = pcall(function() return anim8.newAnimation(frames, dur) end)
    if not animSuccess then
        state.errorMessage = "Failed to create animation."
        state.animation = nil
        return
    end
    
    state.animation = anim
    
    -- Store frame data compactly for writing to unified manifest
    state.generatedFrameData = {
        frameW   = tonumber(state.inputState.frameWidth.text)  or 32,
        frameH   = tonumber(state.inputState.frameHeight.text) or 32,
        left     = tonumber(state.inputState.left.text)   or 0,
        top      = tonumber(state.inputState.top.text)    or 0,
        border   = tonumber(state.inputState.border.text) or 0,
        frames   = table.concat(framesStrArgs, ", "),
        duration = tonumber(state.inputState.duration.text) or 0.1,
    }
    -- Keep legacy generatedCode for any downstream use
    state.generatedCode = string.format([[
local anim8 = require 'anim8.anim8'

return function(image)
    local g = anim8.newGrid(%d, %d, image:getWidth(), image:getHeight(), %d, %d, %d)
    return anim8.newAnimation(g(%s), %s)
end
]],
        tonumber(state.inputState.frameWidth.text)  or 32,
        tonumber(state.inputState.frameHeight.text) or 32,
        tonumber(state.inputState.left.text)   or 0,
        tonumber(state.inputState.top.text)    or 0,
        tonumber(state.inputState.border.text) or 0,
        table.concat(framesStrArgs, ", "),
        state.inputState.duration.text
    )
end

function logic.handleFileDropped(file)
    local ext = file:getFilename():match("^.+(%..+)$")
    if ext then ext = ext:lower() end
    if ext == ".png" or ext == ".jpg" or ext == ".jpeg" then
        file:open("r")
        state.fileData = file:read("data")
        state.image = love.graphics.newImage(state.fileData)
        
        state.animation = nil
        state.generatedCode = ""
        state.errorMessage = ""
        state.selectedFrames = {}
        logic.updateGrid()
    end
end

-- ── Shared: write the unified animations.lua manifest to disk ────────────
local function writeManifest(exportDir, entity, allSlots)
    -- Build the animations table block
    local lines = {
        "-- assets/animations/" .. entity .. "/animations.lua",
        "-- Auto-generated by Anim8tor. Do not hand-edit individual anim files.",
        "",
        "return {",
        "    spritesheet = \"assets/animations/" .. entity .. "/spritesheet.png\",",
        "",
        "    animations = {",
    }
    for name, def in pairs(allSlots) do
        table.insert(lines, string.format(
            "        %-12s= { frameW=%d, frameH=%d, left=%d, top=%d, border=%d, frames=\"%s\", duration=%s },",
            name .. " ",
            def.frameW, def.frameH, def.left, def.top, def.border,
            def.frames, tostring(def.duration)
        ))
    end
    table.insert(lines, "    },")
    table.insert(lines, "}")
    local content = table.concat(lines, "\n")

    local path = exportDir .. "/animations.lua"
    local f, err = io.open(path, "w")
    if not f then return false, err end
    f:write(content)
    f:close()
    return true
end

-- ── Load the current manifest from disk (or return empty table) ───────────
local function readManifestSlots(exportDir)
    local path = exportDir .. "/animations.lua"
    local chunk, _ = loadfile(path)
    if not chunk then return {} end
    local ok, data = pcall(chunk)
    if not ok or type(data) ~= "table" then return {} end
    return data.animations or {}
end

function logic.saveToDisk()
    -- saveToDisk now redirects to bindAndSave logic; kept for back-compat
    logic.bindAndSave()
end

function logic.bindAndSave()
    if not state.generatedFrameData or not state.image then
        state.errorMessage = "Select frames first!"
        return
    end

    local entity   = state.inputState.entityType.text
    local template = state.selectedTemplate
    if entity == "" then entity = "player" end
    if template == "" then template = "walk_down" end

    state.inputState.exportName.text = template

    local baseDir   = love.filesystem.getSource()
    local exportDir = baseDir .. "/assets/animations/" .. entity
    os.execute('mkdir "' .. exportDir:gsub("/", "\\") .. '" 2>nul')
    os.execute('mkdir -p "' .. exportDir .. '" 2>/dev/null')

    -- Write spritesheet
    if state.fileData then
        local f2 = io.open(exportDir .. "/spritesheet.png", "wb")
        if f2 then
            f2:write(state.fileData:getString())
            f2:close()
        end
    end

    -- Read existing manifest slots, merge this slot, write back
    local slots = readManifestSlots(exportDir)
    slots[template] = state.generatedFrameData

    local ok, err = writeManifest(exportDir, entity, slots)
    if not ok then
        state.errorMessage = "Failed to write manifest: " .. tostring(err)
        return
    end

    -- Mark saved in session
    state.savedSlots[template] = true
    state.errorMessage = ""

    -- Invalidate animation cache so the game reflects changes immediately
    local AnimationManager = require("core.animation")
    AnimationManager.invalidate(entity)

    local Console = require("core.console")
    if Console then
        Console.log("[Anim8tor] Bound [" .. template .. "] → animations.lua (" .. entity .. ")", {0,1,0})
    end
end

function logic.exportBindings()
    -- exportBindings is now a no-op: the unified manifest IS the bindings.
    -- All slots are already in animations.lua. This button now just confirms.
    local entity = state.inputState.entityType.text
    if entity == "" then entity = "player" end

    if not next(state.savedSlots) then
        state.errorMessage = "Nothing bound yet! Use BIND & SAVE first."
        return
    end

    local Console = require("core.console")
    if Console then
        Console.log("[Anim8tor] All " .. tostring(#state.savedSlots) ..
            " slots already saved to animations.lua for: " .. entity, {0,1,1})
    end
    state.errorMessage = ""
end

return logic
